! FRR configuration
!
hostname sapinet
log syslog
service password-encryption
service integrated-vtysh-config
!
frr defaults traditional
hostname sapinet
service integrated-vtysh-config
log syslog informational

router ospf
  ospf router-id 10.254.0.1
  passive-interface default
  no passive-interface wgtransport
  network 10.254.0.1/32 area 0
  network 10.255.0.0/24 area 0

router bgp 65000
  bgp router-id 10.254.0.1

  neighbor 10.255.0.2 remote-as 65000
  neighbor 10.255.0.2 update-source wgtransport
  neighbor 10.255.0.2 ebgp-multihop 5

  address-family ipv4 unicast
    network 10.254.0.1/32
    network 10.255.0.0/24
    neighbor 10.255.0.2 activate
  exit-address-family

!
end
