---
# Handlers for common role

- name: Reload sysctl
  ansible.builtin.command: sysctl --system
  listen: Reload sysctl

- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted
  listen: Restart sshd
