[spine]
[leaf]
[hybrid:children]
spine
leaf

[all:vars]
ansible_python_interpreter=/run/current-system/sw/bin/python3

rtr-noisy ansible_host=HOST_IP_rtr-noisy
rtr-sapinet ansible_host=HOST_IP_rtr-sapinet
