---
# handlers file for test_role

- name: restart test_role
  ansible.builtin.service:
    name: "{{ test_role_service_name | default('test_role') }}"
    state: restarted
  listen: restart test_role

- name: reload test_role
  ansible.builtin.service:
    name: "{{ test_role_service_name | default('test_role') }}"
    state: reloaded
  listen: reload test_role
